--- 

- name: create car
  become: yes
  become_user: pi
  shell: |
    /home/pi/venv/bin/donkey createcar --path /home/pi/mycar

- name: modifie the car conf
  template:
    src: myconfig.py.j2
    dest: /home/pi/mycar/myconfig.py

- name: Create donkeycar service for launch manage.py start at startup
  template:
    src: donkeycar.service.j2
    dest: /etc/systemd/system/donkeycar.service
    owner: root
    group: root
  notify: Start donckeycar.service service

- name: Install CarManager requirements
  become: yes
  become_user: pi
  copy:
    src: requirements.txt
    dest: /home/pi/mycar/requirements.txt

- name: Install CarManager part dependencies
  become: yes
  become_user: pi
  pip:
    requirements: /home/pi/mycar/requirements.txt
    virtualenv: /home/pi/venv/
    virtualenv_command: /usr/bin/python3 -m venv

- name: Install CarManager part
  become: yes
  become_user: pi
  copy:
    src: car_manager.py
    dest: /home/py/mycar/car_manager.py

- name: Install custom manage.py
  become: yes
  become_user: pi
  copy:
    src: manage.py
    dest: /home/py/mycar/manage.py

- name: ramfs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: tmpfs /home/pi/mycar/data tmpfs defaults,size=200M,mode=1700,uid=pi,gid=pi,noexec,nodev,nosuid 0 0
    create: yes
