--- 

- name: Create car
  become: yes
  become_user: pi
  shell: |
    /home/pi/venv/bin/donkey createcar --path /home/pi/mycar

- name: Install the (default) car config
  ansible.builtin.copy:
    src: myconfig.py
    dest: /home/pi/mycar/myconfig.py
    owner: pi
    group: pi

- name: Install donkeycar service for launch manage.py start at startup
  become: yes
  template:
    src: donkeycar.service.j2
    dest: /etc/systemd/system/donkeycar.service
    owner: root
    group: root
  notify: Start donckeycar.service service

- name: Ramfs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: tmpfs /home/pi/mycar/data tmpfs defaults,size=200M,mode=1700,uid=pi,gid=pi,noexec,nodev,nosuid 0 0
    create: yes

- name: Install custom joystick
  ansible.builtin.copy:
    src: my_joystick.py
    dest: /home/pi/mycar/my_joystick.py
    owner: pi
    group: pi
    mode: u=r,g=rw,o=rw

- name: Install custom python submodule
  ansible.builtin.copy:
    src: custom
    dest: /home/pi/mycar/
    owner: pi
    group: pi
    mode: u=r,g=rw,o=rw

- name: Install CarManager requirements
  become: yes
  become_user: pi
  copy:
    src: requirements.txt
    dest: /home/pi/mycar/requirements.txt

- name: Install custom manage.py
  become: yes
  become_user: pi
  copy:
    src: manage.py
    dest: /home/pi/mycar/manage.py

- name: Install CarManager part dependencies
  become: yes
  become_user: pi
  pip:
    requirements: /home/pi/mycar/requirements.txt
    virtualenv: /home/pi/venv/
    virtualenv_command: /usr/bin/python3 -m venv
