--- 

- name: create car
  become: yes
  become_user: pi
  shell: |
    /home/pi/venv/bin/donkey createcar --path /home/pi/mycar

- name: modifie the car conf
  template:
    src: myconfig.py.j2
    dest: /home/pi/mycar/myconfig.py

