# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: donkeycar
      POSTGRES_USER: donkeycarmanager
      POSTGRES_DB: donkeycarmanager
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ntp:
    image: donkey/ntp
    build: ./ntp
    restart: always
    ports:
      - 123:123/udp

  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data/ftp_data:/home/donkeycarlph/"
      - "./data/ftp_passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "${SERVER_LOCAL_IP_ADDR}"
      FTP_USER_NAME: donkeycarlph
      FTP_USER_PASS: donkeycarlph
      FTP_USER_HOME: /home/donkeycarlph
    restart: always
