---
- name: Install dependencies
  become: yes
  apt:
    pkg:
      - build-essential 
      - python3 
      - python3-dev 
      - python3-venv
      - python3-pip 
      - python3-virtualenv 
      - i2c-tools 
      - avahi-utils 
      - joystick 
      - libopenjp2-7-dev 
      - libtiff5-dev 
      - gfortran 
      - libatlas-base-dev 
      - libopenblas-dev 
      - libhdf5-serial-dev 
      - libgeos-dev 
      - git 
      - ntp
    state: latest

- name: Create projects directory
  become: yes
  become_user: pi
  file:
    path: /home/pi/projects
    state: directory

- name: Clone the donkeycar repository and checkout in main branch 
  become: yes
  become_user: pi
  ansible.builtin.git:
    repo: https://github.com/autorope/donkeycar.git
    dest: /home/pi/projects/
    force: yes
    single_branch: yes
    version: main

- name: Create python3 virtual environment & install tensorflow
  become: yes
  become_user: pi
  pip:
    name: 
      - https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.2.0/tensorflow-2.2.0-cp37-none-linux_armv7l.whl
      # setuptools 66.0.0 and above enforces semvers, and breaks with the current donkeycar's version
      - setuptools<66.0.0
    virtualenv: /home/pi/venv/
    virtualenv_command: /usr/bin/python3 -m venv

- name: Install evdev
  become: yes
  become_user: pi
  pip:
    name: evdev
    virtualenv: /home/pi/venv/
    virtualenv_command: /usr/bin/python3 -m venv

- name: Add virtualenv activation in bashrc file for pi user
  become: yes
  become_user: pi
  lineinfile:
    dest: /home/pi/.bashrc
    line: "source ~/venv/bin/activate"

- name: run setup.py
  become: yes
  become_user: pi
  pip:
    chdir: /home/pi/projects/
    name: .[pi]
    virtualenv: /home/pi/venv/
    extra_args: '-e'

- name: Install pigpio
  become: yes
  apt:
    pkg:
    - pigpio 
    - python3-pigpio
    state: latest
  notify: Start pigpiod service

- name: Install python dependencies
  become: yes
  become_user: pi
  pip:
    name: 
      - pigpio
      - numpy==1.21.6
      - picamera
      - pandas
      - rpi.gpio
      - protobuf==3.20.*
    virtualenv: /home/pi/venv/
    virtualenv_command: /usr/bin/python3 -m venv
