---

- name: Install git
  become: true
  apt: 
    name: git 
    state: latest

- name: Create the /etc/donkeycar directory
  file:
    path: /etc/donkeycar
    state: directory

- name: Install jsfw
  ansible.builtin.git:
    repo: https://github.com/viandoxdev/jsfw.git
    dest: /home/pi/jsfw
    version: a4b69eb0a115e7fd862dd5e3bc20a3561ea9bcc6

- name: Compile jsfw
  shell:
    cmd: make jsfw
    creates: /home/pi/jsfw/jsfw
    chdir: /home/pi/jsfw

- name: Install jsfw service file
  become: yes
  ansible.builtin.copy:
    src: jsfw.service
    dest: /etc/systemd/system/jsfw.service
    owner: root
    group: root
  notify: Start jsfw.service service

- name: Install jsfw client configuration
  become: yes
  ansible.builtin.copy:
    src: jsfw.json
    dest: /etc/donkeycar/jsfw.json
    owner: root
    group: root

- name: Install the test pictures script
  become: yes
  ansible.builtin.copy:
    src: picture.sh
    dest: /etc/donkeycar/picture.sh
    owner: root
    group: root
    mode: '0755'

- name: Create the environment file for led color
  become: yes
  template:
    src: ds4drv.env.j2
    dest: /etc/donkeycar/ds4drv.env
    owner: root
    group: root
