---
# This playbook contains first time setup of this shit

- name: Install script
  template:
    src: pre-net.j2
    dest: "/usr/local/sbin/pre-net.sh"
    mode: u=rwx,g=rx,o=rx

- name: Copy systemd service file
  template:
    src: pre-net.service.j2
    dest: /etc/systemd/system/pre-net.service
    owner: root
    group: root
  notify:
    - Start pre-net service
