---
- name: modifie config.txt to take charge IR
  lineinfile:
    dest: /boot/config.txt
    line: dtoverlay=gpio-ir,gpio_pin=17
    owner: root
    group: root

- name: Add IR module activation in rc.local
  become: yes
  lineinfile:
    dest: /etc/rc.local
    insertbefore: '^exit 0'
    line: ir-keytable -v -p nec

- name: Install ir-keytable
  become: yes
  apt:
    pkg:
      - ir-keytable
    state: latest
