---
# This playbook deploys the whole DonkeyCar framework.

- name: apply common configuration to all cars
  hosts: all
  remote_user: pi

  roles:
    - role: raspi-config #rasperry pi confiuguration role
      become: yes # This role need root privileges
    - role: car-config  # car configurations (ntp, hostname, ds4drv...)
      become: yes 
    - role: shutdown-btn # shutdown button service
      become: yes 
    - role: ps4-controller # install and configure ds4drv
      become: no
    - role: openCV # Install openCV (optional)
      become: yes 
    - role: donkeycar # Donkeycar installation 
      become: no 
    - role: mycar # create car with configurations
      become: no 
    - role: IR-lap-timer # install dependencies for take charge IR counter
      become: yes 
    - role: optimizations # Remove some expensive and useless things
      become: yes
