---
# This playbook deploys the whole DonkeyCar framework.

- name: apply common configuration to all cars
  hosts: all
  remote_user: pi

  roles:
    - role: raspi-config #rasperry pi confiuguration role
      become: yes # This role need root privileges
    - role: car-config
      become: yes
    - role: shutdown-btn # shutdown button service
      become: yes # This role need root privileges
    - role: ps4-controller # install and configure ds4drv
      become: no # This role no need root privileges
    - role: openCV # Install openCV (optional)
      become: yes # This role need root privileges
    - role: donkeycar # Donkeycar installation 
      become: no # This role doesn't need root privileges
    - role: mycar # create car with configurations
      become: no # This role no need root privileges
    - role: IR-lap-timer # install dependencies for take charge IR counter
      become: yes # This role need root privileges
    - role: optimizations # Remove some expensive and useless things
      become: yes
