---
# This playbook deploys the whole DonkeyCar framework.

- name: apply common configuration to all cars
  hosts: all
  remote_user: pi

  roles:
    - role: raspi-config #rasperry pi configuration role
      become: yes # This role need root privileges
    - role: donkeycar # Donkeycar installation 
      become: no # This role doesn't need root privileges
    - role: openCV
      become: yes
    - role: shutdown-btn # shutdown button service
      become: yes # This role need root privileges
    - role: mycar # shutdown button service
      become: no # This role need root privileges
    - role: hostname
      become: yes
