--- 
- name: Put rules in /etc/udev/rules.d/
  become: yes
  command: wget https://raw.githubusercontent.com/chrippa/ds4drv/master/udev/50-ds4drv.rules -O /etc/udev/rules.d/50-ds4drv.rules

- name: reload ds4drv rules
  become: yes
  command: udevadm control --reload-rules

- name: activate rules
  become: yes
  command: udevadm trigger

- name: Clone the ds4drv repository in /home/pi
  ansible.builtin.git:
    repo: https://github.com/Benvii/ds4drv.git
    dest: /home/pi/
    force: yes
    single_branch: yes
    version: 193_limit_simultaneous_controllers

- name: run setup.py
  pip:
    chdir: /home/pi/ds4drv
    name: setup.py
    virtualenv: /home/pi/venv/
    extra_args: '-e'
  
- name: reload systemctl
  become: yes
  command: systemctl daemon-reload

- name: Copy systemd service file to server
  become: yes
  template:
    src: ds4drv-service.j2
    dest: /etc/systemd/system/ds4drv.service
    owner: root
    group: root
  notify:
    - Start ds4drv service
